- name: install ufw
  apt: >
    pkg=ufw
    state=installed

- name: allow ssh
  sudo: yes
  ufw: >
    proto=tcp
    port={{ ssh_port }}
    rule=allow

- name: set firewall default policy
  sudo: yes
  ufw: >
    state=enabled
    policy=reject

